SELECT DISTINCT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID,
           COUNT(*) OVER (PARTITION BY USER_ID, PRODUCT_ID) AS cnt
    FROM ONLINE_SALE
) T
WHERE cnt > 1
ORDER BY USER_ID, PRODUCT_ID DESC;