# PRODUCT 테이블과 OFFLINE_SALE 테이블에서 상품코드(P.PRODUCT_CODE)별 매출액(SALES = 판매가(P.PRICE) * 판매량(O.SALES_AMOUNT)) 합계를 출력
# 결과는 매출액(SALES)을 기준으로 내림차순(DESC) 정렬해주시고 매출액이 같다면 상품코드(P.PRODUCT_CODE)를 기준으로 오름차순 정렬

SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE;

# -- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
# FROM PRODUCT AS P, OFFLINE_SALE AS OS
# WHERE P.PRODUCT_ID = OS.PRODUCT_ID
# GROUP BY P.PRODUCT_CODE
# ORDER BY SALES DESC, P.PRODUCT_CODE;