SELECT *
FROM (
    (SELECT 0 AS HOUR, 0 AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR)
    UNION ALL
    (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR)
) AS T
ORDER BY HOUR;

# WITH RECURSIVE TimeTable AS (
#     SELECT 0 AS HOUR
#     UNION ALL
#     SELECT HOUR + 1 FROM TimeTable WHERE HOUR < 23
# )

# SELECT 
#     T.HOUR, 
#     COUNT(A.DATETIME) AS 'COUNT'
# FROM TimeTable T
# LEFT JOIN ANIMAL_OUTS A ON T.HOUR = HOUR(A.DATETIME)
# GROUP BY T.HOUR
# ORDER BY T.HOUR;